client_name: mysyara
agent_name: "Mysyara-Test-Agent"
mode: SIP # SIP, CONSOLE
record_audio: True
audio_record_location: azure #azure/s3

store_transcription:
  switch: True # True, False
  where: azure # local, s3, both, azure

welcome_msg: True
use_rag: False
rag_file: "blank"
bg_office_noise: False
bg_thinking_sound: False
idle_call_hungup: True

LLM: 
  primary_provider: azure #openai/azure/gemini
  primary_model: gpt4o #gpt4o/gpt4/5/gemini_model names

  fallback_provider: openai
  fallback_model: gpt5



TTS: 
  primary_provider: cartesia # elevenlabs/cartesia/aws/neuphonic/deepgram - azure/playai is not working currently.
  primary_model: None

  secondary_provider: deepgram
  secondary_model: None


STT: 
  primary_provider: assemblyai #deepgram/assemblyai
  primary_model: None

  secondary_provider: deepgram
  secondary_model: None

idle_call_watcher_msg: "Hello there! Could you please respond? I am here to help."