client_name: mysyara
agent_name: "Mysyara-Test-Agent"
mode: SIP # SIP, CONSOLE
record_audio: True
audio_record_location: azure #azure/s3

store_transcription:
  switch: True # True, False
  where: azure # local, s3, both, azure

welcome_msg: True
use_rag: False
rag_file: "blank"
bg_office_noise: False
bg_thinking_sound: False
idle_call_hungup: True

llm: openai
model: gpt4o

TTS: cartesia # elevenlabs/cartesia/aws/neuphonic/deepgram - azure/playai is not working currently.

STT: assemblyai #deepgram/assemblyai
idle_call_watcher_msg: "Hello there! Could you please respond? I am here to help."