list_of_locations = [
  "Abu Dhabi", 
  "Dubai", 
  "Sharjah", 
  "Ajman", 
  "Umm Al Quwain", 
  "Ras Al Khaimah", 
  "Fujairah",
  "Al Ain", 
  "Al Bateen", 
  "Al Falah", "Al Karamah", "Al Khalidiyah", "Al Khubeirah", "Al Maqtaa",
  "Al Markaziyah", "Al Maryah Island", "Al Mushrif", "Al Muroor", "Al Nahyan", "Al Raha Beach",
  "Al Raha Gardens", "Al Reem Island", "Al Reef", "Al Samha", "Al Shamkha", "Al Wahda", "Bani Yas",
  "Corniche (Abu Dhabi)", "Khalifa City A", "Khalifa City B", "Shakhbout City", "Madinat Zayed",
  "Mohammed Bin Zayed City", "MBZ City", "Musaffah", "Saadiyat Island", "Shahama", "Yas Island",
  "Al Barari", "Al Barsha", "Al Garhoud", "Al Jaddaf", "Al Karama", "Al Khawaneej", "Al Mamzar",
  "Al Manara", "Al Nahda (Dubai)", "Al Quoz", "Al Qusais", "Al Safa", "Al Satwa", "Al Sufouh",
  "Al Warqa'a", "Arabian Ranches", "Barsha Heights", "Tecom", "Bur Dubai", "Business Bay", "Deira",
  "DIFC", "Discovery Gardens", "Downtown Dubai", "Dubai Hills Estate", "Dubai Investment Park",
  "DIP", "Dubai Marina", "Dubai Silicon Oasis", "DSO", "Dubai Sports City", "Emirates Hills",
  "International City", "Jebel Ali", "JLT", "Jumeirah Lakes Towers", "JBR", "Jumeirah Beach Residence",
  "Jumeirah", "Jumeirah Village Circle", "JVC", "Jumeirah Village Triangle", "JVT", "Meadows",
  "Mirdif", "Motor City", "Nad Al Sheba", "Oud Metha", "Palm Jumeirah", "Ras Al Khor", "The Greens",
  "The Springs", "Umm Suqeim", "Al Bu Tina", "Al Ghuwair", "Al Heerah", "Al Khan", "Al Layyeh",
  "Al Majaz", "Al Mamzar (Sharjah)", "Al Mina Street", "Al Nahda (Sharjah)", "Al Nud", "Al Qadisiya",
  "Al Qasba", "Al Qasimia", "Al Rahmaniya", "Al Taawun", "Al Yarmouk", "Corniche (Sharjah)",
  "Maysaloon", "Muwailih", "Rolla Area", "Sharqan", "University City", "Al Bustan", "Al Hamidiya",
  "Al Jurf", "Al Mowaihat", "Al Nakhil", "Al Nuaimiya", "Al Owan", "Al Rashidiya (Ajman)",
  "Al Rumailah", "Al Tallah", "Ajman Downtown", "Corniche (Ajman)", "Garden City", "Liwara"]

keywords_to_boost = [
  "Fujairah",
  "Ras Al Khaimah",
  "Umm Al Quwain",
  "Al Ain",
  "Ras Al Khor",
  "Deira",
  "Al Quoz",
  "Rashidiya",
  "Mirdif",
  "Umm Ramool",
  "Wadi Al Amardi",
  "Mussafah",
  "Rawda",
  "Dubai",
  "Abu Dhabi",
  "Sharjah",
  "Ajman",
  "Mysyara"
]